"""03_remove_relate_voting_options

Revision ID: 2d2b8e117394
Revises: 9b8182b1b69f
Create Date: 2025-11-25 14:20:17.483391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d2b8e117394'
down_revision: Union[str, Sequence[str], None] = '9b8182b1b69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('options_ibfk_2'), 'options', type_='foreignkey')
    op.drop_column('options', 'voting_id')
    op.alter_column('votings', 'archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votings', 'archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.add_column('options', sa.Column('voting_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('options_ibfk_2'), 'options', 'votings', ['voting_id'], ['id'])
    # ### end Alembic commands ###
